name: rssi_monitor_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image: ^4.2.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.0
  google_maps_flutter: ^2.2.0
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
